Added sample skeleton apps for Java, ASPNET, and Node.js
box/samples pull request #2
Opened 2017-02-20 21:34 UTC by amgrobelny-box

2017-02-21 22:18 UTC, mself requested changes

2017-02-21 22:18 UTC, mself commented on box-node-express-skeleton-app/README.md
> +Additionally, since you manage the identity and authorization for your Box App Users within your ASPNET MVC application, you'll need an identity service to fully utilize JWT authentication on behalf
Looks like cut and paste reference to ASPNET in the Node readme

2017-02-21 22:28 UTC, amgrobelny-box commented
Nice catch! Definitely a copy/paste error.

2017-02-21 22:41 UTC, mself requested changes

2017-02-21 22:41 UTC, mself commented on box-node-express-skeleton-app/LICENSE
> +The MIT License (MIT)
I think we're supposed to use Apache-2.0

2017-02-21 22:41 UTC, mself commented on box-node-express-skeleton-app/package.json
> +  "author": "AMSXBG",
Can you switch to:
  "author": "Box <oss@box.com>",
  "license": "Apache-2.0"

2017-02-22 01:22 UTC, amgrobelny-box commented
Made various changes, including those outlined here and that we discussed on chat!

2017-04-18 02:58 UTC, KarthikShanmugasundaram commented
Matthew Self review comments were addressed.

2017-04-18 02:58 UTC, merged