Cognito integration
box/samples pull request #5
Opened 2017-03-27 17:18 UTC by KarthikShanmugasundaram

2017-03-29 21:41 UTC, KarthikShanmugasundaram commented
@manishPh @spiderworm - Could you please review the pull request?

2017-03-30 17:06 UTC, spiderworm requested changes

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/createAppUser/aws-service.js
> +class AWSService {
One filename convention that's starting to come to JavaScript with better modularization is to have file names reflect exactly the name of the class exported by that file, so in this case, you might consider naming the file AWSService.js so that it reflects the exact module name that is exported here.

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/createAppUser/aws-service.js
> +'use strict';
ES6/ES2015 modules are already in strict mode (here's some info: http://stackoverflow.com/questions/31685262/not-recommended-to-use-use-strict-in-es6)

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/createAppUser/aws-service.js
> +        this.AWS = require('aws-sdk');
Typically you would import dependencies at the beginning of the file, before the class definition or any other code, but you may have a reason for doing this here. If there is no compelling reason to import here rather than at the top of the module, move this to the top.

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/createAppUser/box-manager.js
> +'use strict';
No need for use strict

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/createAppUser/box-manager.js
> +let BoxSdk = new Box({
BoxSdk could be a const here

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/createAppUser/box-manager.js
> +    let requestParams = {
const

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/createAppUser/box-manager.js
> +  	let boxAdminClient = BoxSdk.getAppAuthClient('enterprise', process.env.BOX_ENTERPRISE_ID);
const

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/createAppUser/cognito-manager.js
> +'use strict'
no use strict

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/createAppUser/cognito-manager.js
> +let cognitoClient = awsService.getCognitoClient();
const

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/createAppUser/cognito-manager.js
> +let updateUserAttribute = function (userPoolId, userName, appUserId) {
const

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/createAppUser/cognito-manager.js
> +    let params = {
const

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/createAppUser/cognito-manager.js
> +let adminGetUser = function(event) {
const

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/createAppUser/cognito-manager.js
> +     let params = {
const

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/createAppUser/box-manager.js
> +}
semicolon. It's a common Node.JS to omit semicolons (although I see you do include them for most of your code), but it's a bad practice (just ask Doug Crockford). You'll never forget the day you run into a bug caused by code that looks something like this:

var myThing = {
 // some properties
}

(function() { /* some code to execute now */ })();

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/createAppUser/aws-service.js
> +}
semicolon

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/createAppUser/box-manager.js
> +}
semicolon

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/createAppUser/cognito-manager.js
> +}
semicolon

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/createAppUser/cognito-manager.js
> +}
semicolon

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/createAppUser/cognito-manager.js
> +}
semicolon

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/createAppUser/cognito-manager.js
> +}
semicolon

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/createAppUser/index.js
> +"use strict";
no use strict

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/createAppUser/index.js
> +}
semicolon

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/tokenExchange/aws-service.js
> +'use strict';
no use strict

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/tokenExchange/aws-service.js
> +        this.AWS = require('aws-sdk');
require above class definition instead? also, why use "require" instead of "import"?

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/tokenExchange/box-manager.js
> +}
semicolon

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/tokenExchange/box-manager.js
> +}
semicolon

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/tokenExchange/box-manager.js
> +'use strict';
no strict

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/tokenExchange/box-manager.js
> +let BoxSdk = new Box({
const

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/tokenExchange/box-manager.js
> +let generateUserToken = function (appUserId) {
const

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/tokenExchange/cognito-manager.js
> +'use strict';
no strict

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/tokenExchange/cognito-manager.js
> +let cognitoClient = awsService.getCognitoClient();
const

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/tokenExchange/cognito-manager.js
> +let getAppUserProperty = function (attributes) {
const

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/tokenExchange/cognito-manager.js
> +    var appUserId = _.find(attributes, function (attr) {
const, probably

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/tokenExchange/cognito-manager.js
> +let getUser = function(token) {
const

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/tokenExchange/cognito-manager.js
> +let adminGetUser = function(user) {
const

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/tokenExchange/cognito-manager.js
> +	let userAttributesParams = {
const

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/tokenExchange/cognito-manager.js
> +}
semicolon

2017-03-30 17:06 UTC, spiderworm commented on box-node-cognito-lambdas-sample/tokenExchange/index.js
> +'use strict'
no strict

2017-03-30 17:06 UTC, spiderworm commented on box-node-rekognition-lambdas-sample/rekognition/index.js
> +'use strict';
no strict

2017-03-30 17:06 UTC, spiderworm commented on box-node-rekognition-lambdas-sample/rekognition/index.js
> +var AWS = require('aws-sdk');
const, probably

2017-03-30 17:06 UTC, spiderworm commented on box-node-rekognition-lambdas-sample/rekognition/index.js
> +var rekognition = new AWS.Rekognition({apiVersion: '2016-06-27'});
const, probably

2017-03-30 17:06 UTC, spiderworm commented on box-node-rekognition-lambdas-sample/rekognition/index.js
> +var sdk = new BoxSDK({
const

2017-03-30 17:06 UTC, spiderworm commented on box-node-rekognition-lambdas-sample/rekognition/index.js
> +// var client = sdk.getBasicClient(token);
dead code? if you dont need it, kill it

2017-03-30 17:06 UTC, spiderworm commented on box-node-rekognition-lambdas-sample/rekognition/index.js
> +}
semicolon

2017-03-30 17:06 UTC, spiderworm commented on box-node-rekognition-lambdas-sample/rekognition/index.js
> +}
semicolon

2017-03-30 17:06 UTC, spiderworm commented on box-node-rekognition-lambdas-sample/webhook/index.js
> +'use strict';
no strict

2017-03-30 17:06 UTC, spiderworm commented on box-node-rekognition-lambdas-sample/webhook/index.js
> +var BoxSDK = require('box-node-sdk');
const

2017-03-30 17:06 UTC, spiderworm commented on box-node-rekognition-lambdas-sample/webhook/index.js
> +var AWS = require('aws-sdk');
const

2017-03-30 17:06 UTC, spiderworm commented on box-node-rekognition-lambdas-sample/webhook/index.js
> +var dbClient = new AWS.DynamoDB.DocumentClient();
const

2017-03-30 17:06 UTC, spiderworm commented on box-node-rekognition-lambdas-sample/webhook/index.js
> +}
semicolon

2017-03-30 17:06 UTC, spiderworm commented on box-node-rekognition-lambdas-sample/webhook/index.js
> +        })
semicolon

2017-04-14 18:13 UTC, KarthikShanmugasundaram commented
review comments are fixed

2017-04-14 18:14 UTC, merged